"""Utilities for operating on arrays from different deep learning and linear algebra frameworks."""

from __future__ import annotations

from ._decorators import autodecorate_cost_method
from ._functions import (
    argmax,
    argmin,
    astype,
    copy,
    eye,
    eye_like,
    get_item,
    max,  # noqa: A004
    mean,
    min,  # noqa: A004
    norm,
    numpy_to_array,
    numpy_to_array_like,
    ones_like,
    rand_like,
    randn_like,
    reshape,
    set_item,
    shape,
    stack,
    sum,  # noqa: A004
    to_array,
    to_jax,
    to_numpy,
    to_tensorflow,
    to_torch,
    transpose,
    zeros,
    zeros_like,
)
from ._operators import (
    absolute,
    add,
    div,
    dot,
    iadd,
    idiv,
    imul,
    ipow,
    isub,
    matmul,
    mul,
    negative,
    power,
    sqrt,
    sub,
)

__all__ = [  # noqa: RUF022
    # From _functions
    "argmax",
    "argmin",
    "astype",
    "copy",
    "eye",
    "eye_like",
    "get_item",
    "max",
    "mean",
    "min",
    "norm",
    "numpy_to_array",
    "numpy_to_array_like",
    "ones_like",
    "rand_like",
    "randn_like",
    "reshape",
    "set_item",
    "shape",
    "stack",
    "sum",
    "to_array",
    "to_numpy",
    "to_torch",
    "to_tensorflow",
    "to_jax",
    "transpose",
    "zeros",
    "zeros_like",
    # From _operators
    "absolute",
    "add",
    "div",
    "dot",
    "iadd",
    "idiv",
    "imul",
    "ipow",
    "isub",
    "matmul",
    "mul",
    "negative",
    "power",
    "sqrt",
    "sub",
    # From _helpers
    "autodecorate_cost_method",
]
