# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "decent-bench"
copyright = "2025, Team Decent"
author = "team-decent"

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

import os
import sys

from docutils import nodes

sys.path.insert(0, os.path.abspath("../.."))

extensions = [
    "sphinx.ext.autodoc",  # Expand rst automodule directives generated by `sphinx-apidoc`
    "sphinx.ext.intersphinx",  # Link to types from external packages
    "sphinx.ext.napoleon",  # Parse Google style docstrings
    "sphinx.ext.viewcode",  # View source code
]

autodoc_default_options = {}
autodoc_member_order = "bysource"
autodoc_preserve_defaults = True
autodoc_type_aliases = {}

nitpicky = True
nitpick_ignore = [
    ("py:class", "numpy.float64"),
    ("py:class", "float64"),
    ("py:class", "numpy._typing._array_like._SupportsArray"),
    ("py:class", "numpy._typing._nested_sequence._NestedSequence"),
    ("py:class", "T"),
    ("py:class", "TorchTensor"),
    ("py:class", "TensorFlowTensor"),
    ("py:class", "JaxArray"),
]

intersphinx_mapping = {
    "networkx": ("https://networkx.org/documentation/stable/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "python": ("https://docs.python.org/3", None),
    "torch": ("https://pytorch.org/docs/stable/", None),
    "matplotlib": ("https://matplotlib.org/stable/", None),
    "tensorflow": (
        "https://www.tensorflow.org/api_docs/python",
        "https://github.com/GPflow/tensorflow-intersphinx/raw/master/tf2_py_objects.inv",
    ),
    "jax": ("https://jax.readthedocs.io/en/latest/", None),
    "rich": ("https://rich.readthedocs.io/en/latest/", None),
}


exclude_patterns = []


# A way to link numpy.typing.ArrayLike and NDArray correctly
# Seems to be an open issue, see https://github.com/sphinx-doc/sphinx/issues/10794
# https://github.com/sphinx-doc/sphinx/issues/10785#issuecomment-1321100925
def _numpy_typing_missing_ref(app, env, node, contnode):
    if node.get("refdomain") == "py" and node.get("reftype") in {"class", "data"}:
        target = node.get("reftarget")
        if target in {"ArrayLike", "numpy.typing.ArrayLike"}:
            return nodes.reference(
                "", "ArrayLike", refuri="https://numpy.org/doc/stable/reference/typing.html#numpy.typing.ArrayLike"
            )
        if target in {"NDArray", "numpy.typing.NDArray"}:
            return nodes.reference(
                "",
                "NDArray",
                refuri="https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray",
            )
    return None


def setup(app):
    app.connect("missing-reference", _numpy_typing_missing_ref)


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "pydata_sphinx_theme"
html_theme_options = {
    "logo": {
        "text": project,
    },
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/team-decent/decent-bench",
            "icon": "fa-brands fa-github",
            "type": "fontawesome",
        },
        {
            "name": "PyPI",
            "url": "https://pypi.org/project/decent-bench/",
            "icon": "fa-solid fa-box-open",
            "type": "fontawesome",
        },
    ],
    "icon_links_label": "Quick Links",
}
html_context = {"default_mode": "auto"}
html_show_sourcelink = False
html_logo = "_static/logo.png"
html_favicon = "_static/logo.png"
html_static_path = ["_static"]
html_css_files = ["custom.css"]
html_sidebars = {
    "author": [],
    "background": [],
    "developer": [],
    "user": [],
}
