# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "decent-bench"
copyright = "2025, team-decent"
author = "team-decent"
release = "0.0.0"

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

import os
import sys

sys.path.insert(0, os.path.abspath("../.."))


extensions = [
    "sphinx.ext.autodoc",  # Expand rst automodule directives generated by `sphinx-apidoc`
    "sphinx.ext.intersphinx",  # Link to types from external packages
    "sphinx.ext.napoleon",  # Parse Google style docstrings
    "sphinx.ext.viewcode",  # View source code
]

autodoc_default_options = {"special-members": "__add__, __iter__"}

autodoc_member_order = "bysource"
autoclass_content = "init"

nitpicky = True
nitpick_ignore = [("py:class", "numpy.float64")]

intersphinx_mapping = {
    "numpy": ("https://numpy.org/doc/stable/", None),
    "python": ("https://docs.python.org/3", None),
}


templates_path = ["_templates"]
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "sphinx_rtd_theme"
